### ISSUE TITLE
oauth help need

### ISSUE THREAD

**Issue by anguskwan** [feathersjs/feathers-authentication#114]
```js
  app.configure(authentication(config));
  app.configure(authentication({
    facebook: {
      strategy: FacebookStrategy,
      "clientID": "xxxxx",
      "clientSecret": "xxxxx",
      "callbackURL": "/auth/facebook/auth",
      "profileFields": [
        "displayName",
        "emails"
      ]
    },
  }))
```
```(node) warning: possible EventEmitter memory leak detected. 7 connection listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Namespace.addListener (events.js:240:17)
    at Server.(anonymous function) [as on] (/Users/anguskwan/macdev/nodejs/feathers-chat/node_modules/socket.io/lib/index.js:369:16)
    at EventEmitter.app.setup (/Users/anguskwan/macdev/nodejs/feathers-chat/node_modules/feathers-authentication/lib/index.js:120:16)
    at EventEmitter.listen (/Users/anguskwan/macdev/nodejs/feathers-chat/node_modules/feathers/lib/application.js:145:10)
    at EventEmitter.listen (/Users/anguskwan/macdev/nodejs/feathers-chat/node_modules/uberproto/lib/proto.js:30:17)
    at Object.<anonymous> (/Users/anguskwan/macdev/nodejs/feathers-chat/src/index.js:5:20)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)

```

based on the feathers-chat code, i added the facebook strategy as above, but something wrong.

cannot figure out a good way to use oauth with feathers-authentication, please help  ：P

**Comment by daffl** [comment]
Does this still happen with the latest version 0.7.0?

**Comment by ekryski** [comment]
Since there is no response here I'm going to close. We can open a new issue around event emitters if we need to. I haven't see this.
