### ISSUE TITLE
auth.express.authenticate got undefined

### ISSUE THREAD

**Issue by jinwyp** [feathersjs/feathers-authentication#363]
Just follow the doc 

app.post('/login', auth.express.authenticate('local', { successRedirect: '/app', failureRedirect: '/login' }));

got error " read property 'authenticate' of undefined"

```
/Users/tttt/Documents/github/featherjsdemo/backend/src/services/user/index.js:40
    app.post('/api/user/password', auth.express.authenticate('jwt'), userInfoController.changePassword(app));
                                               ^

TypeError: Cannot read property 'authenticate' of undefined
    at EventEmitter.module.exports (/Users/tttt/Documents/github/featherjsdemo/backend/src/services/user/index.js:40:48)
    at EventEmitter.configure (/Users/tttt/Documents/github/featherjsdemo/backend/node_modules/feathers/lib/application.js:138:8)
    at EventEmitter.module.exports (/Users/tttt/Documents/github/featherjsdemo/backend/src/services/index.js:15:7)
    at EventEmitter.configure (/Users/tttt/Documents/github/featherjsdemo/backend/node_modules/feathers/lib/application.js:138:8)
    at Object.<anonymous> (/Users/tttt/Documents/github/featherjsdemo/backend/src/app.js:41:6)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/tttt/Documents/github/featherjsdemo/backend/src/index.js:3:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)

```

**Comment by daffl** [comment]
Are you sure you installed version `1.0.0-beta` and not `0.7.x`?

**Comment by jinwyp** [comment]
I installed version 0.7.12,  Should I install 1.0.0-beta to get  auth.express middleware ?

**Comment by daffl** [comment]
Yes

**Comment by jinwyp** [comment]
Thanks.
