### ISSUE TITLE
feathers-authentication errors with any view error, and redirects to /auth/failure

### ISSUE THREAD

**Issue by krisdahl** [feathersjs/feathers-authentication#381]
### Steps to reproduce
First off, my apologies if this is just my ignorance of the feather ecosystem and architecture.  Oer perhaps is a configuration option. Seems odd though, not sure how to resolve.

Add feathers-authentication service to your app.

Set a view engine.
```app.set('view engine', 'handlebars');```

Cause any sort of error in your view logic.  In the case of jade, reference an object that doesn't exist.  Or pick a view engine that you don't have installed, which is what I did for this example.

### Expected behavior

A normal/general feathers 500 error, or stack trace with error relating to the view engine.  Here is example with a missing view engine (handlebars)

From log:

```
feathers-errors GeneralError(500): Cannot find module 'handlebars'
```

or stacktrace:
```Error: Cannot find module 'handlebars'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:289:25)
   at Module.require (module.js:366:17)
   at require (module.js:385:17)
   at new View (/web/feathers-demos/examples/rendering/rendering-templates/node_modules/express/lib/view.js:78:30)
   at EventEmitter.render (/web/feathers-demos/examples/rendering/rendering-templates/node_modules/express/lib/application.js:569:12)
   at ServerResponse.render (/web/feathers-demos/examples/rendering/rendering-templates/node_modules/express/lib/response.js:960:7)
   at Object.feathers.configure.configure.configure.use.use.use.use.use.errorHandler.html [as text/html] (/web/feathers-demos/examples/rendering/rendering-templates/app.js:23:11)
   at /web/feathers-demos/examples/rendering/rendering-templates/node_modules/feathers-errors/lib/error-handler.js:83:36
   at Layer.handle_error (/web/feathers-demos/examples/rendering/rendering-templates/node_modules/express/lib/router/layer.js:71:5)
```
### Actual behavior

feathers-authentication for thinks this is an authentication error, and redirects to /auth/failure.  From debug log:

```
feathers-authentication:middleware An authentication error occurred. { [Error: Cannot find module 'handlebars'] code: 'MODULE_NOT_FOUND' }
```

### System configuration

    "feathers": "^2.0.2",
    "feathers-authentication": "^0.7.11",

**Comment by bertho-zero** [comment]
Try `npm i handlebars -S`

**Comment by daffl** [comment]
Try [upgrading to 1.0.0](https://github.com/feathersjs/feathers-authentication/blob/master/docs/migrating.md) to see if the issue persists.

**Comment by krisdahl** [comment]
I 'upgraded' trying to use migration guide, but have some more work to do to get authentication working again (not super familiar yet with Feathers).
Indeed upgrading to 1.0.0 did work in fixing the error handling problem.  Sorry I should have realized.

I was using the generated boilerplate.  Any ideas when the "feathers generate" will use feathers-authentication 1.0.0?

**Comment by ekryski** [comment]
@krisdahl It will. We're currently working on it. Trying hard to get it wrapped before the new year. Glad you got it sorted. 😄
