### ISSUE TITLE
node can not require("feathers-authentication").default

### ISSUE THREAD

**Issue by wuyuanyi135** [feathersjs/feathers-authentication#53]
I have installed authentication module by
```
npm install --save feathers-authentication
```

the line `var authentication = require ('feathers-authentication').default;` causes
```
/home/wuyuanyi/riddle-web/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/wuyuanyi/riddle-web/node_modules/bcrypt/build/bcrypt_lib.node
 → /home/wuyuanyi/riddle-web/node_modules/bcrypt/build/Debug/bcrypt_lib.node
 → /home/wuyuanyi/riddle-web/node_modules/bcrypt/build/Release/bcrypt_lib.node
 → /home/wuyuanyi/riddle-web/node_modules/bcrypt/out/Debug/bcrypt_lib.node
 → /home/wuyuanyi/riddle-web/node_modules/bcrypt/Debug/bcrypt_lib.node
 → /home/wuyuanyi/riddle-web/node_modules/bcrypt/out/Release/bcrypt_lib.node
 → /home/wuyuanyi/riddle-web/node_modules/bcrypt/Release/bcrypt_lib.node
 → /home/wuyuanyi/riddle-web/node_modules/bcrypt/build/default/bcrypt_lib.node
 → /home/wuyuanyi/riddle-web/node_modules/bcrypt/compiled/4.3.0/linux/x64/bcrypt_lib.node
    at bindings (/home/wuyuanyi/riddle-web/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/wuyuanyi/riddle-web/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/wuyuanyi/riddle-web/node_modules/feathers-authentication/lib/index.js:204:15)
    at Module._compile (module.js:410:26)
```

How could I fix the problem?

**Comment by wuyuanyi135** [comment]
for some reason the bcrypt did not installed properly.
After tried
```
npm install bcrypt
```
this problem gone
