### ISSUE TITLE
Intermittent NotAuthenticated: No auth token 

### ISSUE THREAD

**Issue by dottodot** [feathersjs/feathers-authentication#577]
I have a bizarre issue that I can't find the root cause of and it's only just manifested itself. The request I'm making to a service then has a few hooks that perform updates on other services but every so often during the various updates I get the error `NotAuthenticated: No auth token`. Restarting the feathers app seems to clear it sometimes and then the exact same request will work.

I'm assuming that somehow on occasion my headers are getting removed but I have no idea what would cause that to happen, and I've checked to make sure the header is being sent every time.

**Comment by dottodot** [comment]
Actually just wondering if it might be something to do with my app being reloaded using nodemon as it seems to be after automatic restarts that it then fails. Still no idea why that would be though.

**Comment by daffl** [comment]
Are you using the `softDelete` or other common hooks?

**Comment by dottodot** [comment]
I don't use `softDelete` but use some of the other hooks such as `iffelse`

**Comment by tdolphin** [comment]
Hi, I am new to feathersjs so please bear with me.
I am also getting intermittent authentication issue. All I do is stop the server and run it again and it sometimes works as if there is a race condition somewhere. I fixed it using iff(isProvider('external'),authenticate('jwt')) but this took away authorization when I try to download

I am writing a file upload/download service based on the documentation.
The file actual name, mime type, size are stored in the database. The record id is the name of the stored file on disk.
```javascript
const { authenticate } = require('feathers-authentication').hooks;
const { iff, isProvider, populate } = require('feathers-hooks-common');
const processUpload = require('../../hooks/process-upload');
const finishUpload = require('../../hooks/finish-upload');
module.exports = {
  before: {
    all: [ iff(isProvider('external'),authenticate('jwt')) ],
    find: [],
    get: [],
    create: [processUpload()],
    update: [],
    patch: [],
    remove: []
  },

  after: {
    all: [],
    find: [],
    get: [],
    create: [finishUpload()],
    update: [],
    patch: [],
    remove: []
  },

  error: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
};
```
process-upload.js
```javascript
module.exports = function() {
  return function(hook) {
    // The authenticated user
    const user = hook.params.user;
    if (!hook.data.attchfile && hook.params.file){
      const file = hook.params.file;
      hook.data = {
        filename: file.originalname,
        mimetype: file.mimetype,
        filesize: file.size,
        // Set the user id
        userId: user._id,
        // Add the current time via `getTime`
        createdAt: new Date().getTime()
      };
    }

    return Promise.resolve(hook);
  };
};
```
finish upload hook for renaming the uploaded file as the record id
```javascript
var fs = require('fs');
module.exports = function() {
  return function finishUpload(hook) {
    const storepath = hook.params.file.destination + '/';    
    fs.rename(storepath + hook.params.file.filename, storepath + hook.result._id, function(err) {
      if ( err ) console.log('RENAME FILE ERROR: ' + err);
    });
    return Promise.resolve(hook);
  };
};
```
all this is working fine. I am having a problem with the download route trying to do it as 
```javascript
app.get('/uploads/:fileId/download',...
```
: inside the same /uploads service.
Any hints why this is not the right way are deeply appreciated.
```javascript
// Initializes the `uploads` service on path `/uploads`
const createService = require('feathers-nedb');
const createModel = require('../../models/uploads.model');
const hooks = require('./uploads.hooks');
const { authenticate } = require('feathers-authentication').hooks;

const filters = require('./uploads.filters');
var multer = require('multer');
var path = require('path');
var fs = require('fs');

const imageFilter = function (req, file, cb) {
  // accept image only
  if (!file.originalname.match(/\.(jpg|jpeg|png|gif)$/i)) {
    return cb(new Error('Only image files are allowed!'), false);
  }
  cb(null, true);
};

module.exports = function () {
  const app = this;
  const Model = createModel(app);
  const paginate = app.get('paginate');
  const filestore = app.get('filestore');
  const upload = multer({ dest: filestore, fileFilter: imageFilter });

  const options = {
    name: 'uploads',
    Model,
    paginate
  };

  // Initialize our service with any options it requires
  app.use('/uploads', 
    upload.single('attchfile'),
    function(req,res,next) {
      req.feathers.file = req.file;
      next();
    },
    createService(options)
  );
  // Get our initialized service so that we can register hooks and filters
  const service = app.service('uploads');
  //const service2 = app.service('uploads/:fileId/download');

  service.hooks(hooks);
  //service2.hooks(hooks); //this gives error as service2 is undefined

  app.get('/uploads/:fileId/download',
    function(req,res) {
    //console.log(req.params.fileId);
      var a;
      var promise1 = app.service('uploads').get(req.params.fileId).then(
        function(fileinfo) {
        console.log(fileinfo);
          a = fileinfo;
          const fileondisk = path.join(filestore,''+a._id);
          console.log(fileondisk,a.filename);
          if(!fs.existsSync(fileondisk)) {
            console.log('file not found\n\n');
          } else {
            console.log('file is there!!!\n\n');
            res.sendFile( fileondisk,
              {
                headers: {
                  'Content-Type':a.mimetype,
                 'Content-Disposition':'attachment; filename="'+a.filename+'"',
                 'Content-Length':a.filesize
                }
              },function(err){
                if(err) console.log(err);
              }
            );
          }
        }
      );//.catch(res.status(403).end());
    }
  );

  if (service.filter) {
    service.filter(filters);
  }
};
```

**Comment by marshallswain** [comment]
@tdolphin I haven't run into this issue in any of the projects we've made, so I don't know the cause, but I would recommend adjusting the predicate in the `iff(isProvider('external'),authenticate('jwt'))` if possible.

**Comment by tdolphin** [comment]
so what is the right way to write a service that requires data from another service?

**Comment by marshallswain** [comment]
I generally create a hook for the service that uses `context.app.service('other-service').find()`.

**Comment by tdolphin** [comment]
Thank you. I followed your advice and [https://docs.feathersjs.com/api/express.html#custom-service-middleware](url) and it is now working correctly.
I created a custom service with a dummy class so that I can get a place for the hook to get the data I need then added a middleware that runs after the service. 
What I was trying before was to get the data into the middleware function directly. May be that is not possible?
Sorry for posting all this code here but I searched for a long time and couldn't find a solution so I thought may be this solution may help somebody in the future/
Thanks again.
```javascript
class Service {
  constructor (options) {
    this.options = options || {};
  }
  get (id, params) { 
    return Promise.resolve({id});
  }
}

module.exports = function (options) {
  return new Service(options);
};
module.exports.Service = Service;
```
```javascript
const { authenticate } = require('feathers-authentication').hooks;
module.exports = {
  before: {
    all: [ authenticate('jwt') ]
  },
  after: {
    get: [
      function getdownloadfileinfo (hook) {
        return hook.app.service('uploads').get(hook.result.id).then(fileinfo=> {
          hook.result = fileinfo;
          return hook;
        });
      }  
    ]
  }
```

```javascript
// Initializes the `download` service on path `/download
const createService = require('./download.class.js');
const hooks = require('./download.hooks');
const filters = require('./download.filters');
var path = require('path');
var fs = require('fs');

module.exports = function () {
  const app = this;
  const options = {
    name: 'download',
  };
  const filestore = app.get('filestore');
  app.use('/download', 
    createService(options),
    function(req,res) {   // middleware function here <--
      const a = res.data;
      const fileondisk = path.join(filestore,'' + a._id);
      if(!fs.existsSync(fileondisk)) {
        res.status(404).end();
      } else {
        //console.log('file is there!!!\n\n');
        res.sendFile( fileondisk,
          {
            headers: {
              'Content-Type' : a.mimetype,
              'Content-Disposition' : 'attachment; filename="' + a.filename + '"',
              'Content-Length' : a.filesize
            }
          },function(err){
            if(err) console.log(err);
          }
        );
      }
    }
  );
  const service = app.service('download');
  service.hooks(hooks);
  if (service.filter) {
    service.filter(filters);
  }
};
```

**Comment by marshallswain** [comment]
@tdolphin I'm glad you got it working.  Thank you for being considerate of future users and posting your code.

Also, please let us know if there's any update on the Intermittent NotAuthenticated: No auth token issue.  I'll watch for this in my projects.

**Comment by ekryski** [comment]
@dottodot you still having issues? Otherwise I'm going to close this out as it looks to be resolved for @tdolphin.

**Comment by dottodot** [comment]
Yes I'm still getting it and don't think using `iff(isProvider('external'),authenticate('jwt'))` will help in my case as the requests that are failing are external. The problem I have is it's so intermittent and a restart can mean the same request won't fail on the next attempt.

**Comment by tdolphin** [comment]
Unfortunately, I see it happening again in the same code I posted.
I get authentication error then I just stop the server and start it again and it keeps working.
But at least it is now consistent. First time fails then restart nodejs and it works.
I am using the terminal in visual studio code on a Mac OS10 Sierra and also tried just the terminal and getting this consistently.

**Comment by arranf** [comment]
I am also seeing behaviour like this

**Comment by ekryski** [comment]
@arranf @tdolphin @dottodot any chance one of you can post a link to a git repo that reproduces the issue? We've never seen this on any of our apps so if you can put together something one of us can clone down that would help a ton! 😄

**Comment by travisbmiller** [comment]
I am too running into this error, just like others, restarting it will solve the problem, but it comes back out of no where. I am also using ```iff(isProvider('external'),authenticate('jwt'))```

**Comment by dottodot** [comment]
I think the problem for me is when I use a hook to update something on a different service something like

```
      hook => {
        const Order = hook.app.service('/orders');
        Order.patch(
          null,
          { updatedAt: new Date() },
          {
            query: {
              _id: hook.data.order
            }
          }
        );
      }
```
this means the order service has no auth header and I think that's why it's failing and by passing in query like this, it's probably removing other information such as provider which is maybe why `iff(isProvider('external'),authenticate('jwt'))` doesn't work either. 

If I do the following and pass the original params to the service I don't get an issue.

```
      hook => {
        const Order = hook.app.service('/orders');
        hook.params.query = {
          _id: hook.data.order
        };
        Order.patch(null, { updatedAt: new Date() }, hook.params);
      }
```
Not sure that this is the right thing to do. I would have thought making internal requests should be more straight forward.

**Comment by daffl** [comment]
You should only pick the params that you really want. In you case I'm not sure why you are making a multi-patch when you set the query to just update a single record by id.

```js
hook => {
  const Order = hook.app.service('/orders');
  const params { user: hook.params.user };

  return Order.patch(hook.data.order._id, { updatedAt: new Date() }, params)
    .then(() => hook);
}
```

**Comment by dottodot** [comment]
It was just an example to highlight the issue

**Comment by dottodot** [comment]
I believe the issue is due using populate, at least in my case. If for example I'm trying to populate a field and the service to be populated requires authentication then I get a 401 on the parent. This however doesn't explain why I get an intermittent issue. 

Anyway I'm finding that using [fastJoin](https://feathers-plus.github.io/v1/feathers-hooks-common/guide.html#Usage) seems to work better, I can setup authorisation on a service but also populate in another service without authorisation. Not had chance to convert the problematic project over to fastJoin yet but I'm hopeful it might clear the problem.

**Comment by jamesholcomb** [comment]
After upgrading client and server to Buzzard, I am seeing this behavior as well for `populate`.

For some reason, { provider: 'socketio' } is coming in on options.schema even though this particular `populate` originated out-of-band from an RxJs subscription that processes messages on a queue.  Error is 'No auth token'

Same issue if I initiate the flow via REST.

**Comment by sripathij** [comment]
I am seeing a similar if not the same issue and believe it is related to the populate hook. I am able to consistently reproduce the issue though. I have a file upload service, that uploads to an S3 bucket. Prior to upload it does a context.app.service.find() on another service in the before hook. If there is no data returned, I throw an error and the upload service errors out. This works consistently, without any issue. However, if there is data in the collection in MongoDB, then I receive the Not Authenticated: No auth token error, like so
info: error: users - Method: find: No auth token
error:  NotAuthenticated: No auth token
    at new NotAuthenticated (C:\xxxx\node_modules\@feathersjs\errors\lib\index.js:88:17)
    at app.authenticate.then (C:\xxxx\node_modules\@feathersjs\authentication\lib\hooks\authenticate.js:76:31)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

I restart the server and submit the exact same upload request and it goes through. 

.  I am using feathers 3.6.0 and mongoose. Is there a workaround?

**Comment by jamesholcomb** [comment]
Try adding `provider: undefined` to your `populate` schema hook argument.  That fixed my particular issue.

**Comment by sripathij** [comment]
@jamesholcomb. Thanks, that works for me as well. Looked up the documentation and it makes sense, kind off. If it's optional though as the documentation says it is, this should be considered a bug.

**Comment by EugeneKorshenko** [comment]
Same issue at one of my projects.
